### ISSUE TITLE
HOW to use  the  ColmapForVisSatPatched

### ISSUE THREAD

**Issue by ouyuanzheng** [SBCV/ColmapForVisSatPatches#1]
Hello, may I ask if the patch is used after installing Colmap or directly using the patch file during Colmap installation? I don't quite understand the specific process. Can you provide any suggestions?

**Comment by SBCV** [comment]
As you can see in the [patches](https://github.com/SBCV/ColmapForVisSatPatched/tree/main/patches) folder, the files which are replaced are source files (e.g. [src__base__camera.cc](https://github.com/SBCV/ColmapForVisSatPatched/blob/main/patches/src__base__camera.cc.patch)).

Therefore, the patches must be applied before building the colmap library.

**Comment by ouyuanzheng** [comment]
Thank you very much for your reply!
I want to know the sentence 'Finally, apply the satellite specific patches with:
$PathToColmapForVisSatPatched/apply_ Patches. sh $PathToColmapToBePatched ", what should I do specifically?


When installing colmap after installing this patch. Do I need to perform&nbsp;
“apt get install nvidia driver 390 nvidia utils 390 nvidia cuda toolkit” of “ubuntu1804_install_dependencies.sh”file .



My ubuntu20.04 system has installed nvidia driver-470 and cuda-11.0, but an error occurred during the compilation of colmap. Is it due to the graphics card and cuda that caused the error. Because I have only just started learning about Colmap and there are many things I don't understand. I hope to receive your help. Thank you very much.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月16日(星期天) 晚上7:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SBCV/ColmapForVisSatPatched] HOW to use  the  ColmapForVisSatPatched (Issue #1)





 
As you can see in the patches folder, the files which are replaced are source files (e.g. src__base__camera.cc).
 
Therefore, the patches must be applied before building the project.

**Comment by SBCV** [comment]
Have you build the original colmap library without errors?

**Comment by ouyuanzheng** [comment]
Do you mean to first build the colmap and then use the ColmapForVisSatPatched patch file?


I have built&nbsp; colmap&nbsp;without errors&nbsp;before, but there was a problem where I couldn't find the camera txt file, as shown in the following image:










------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月16日(星期天) 晚上7:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SBCV/ColmapForVisSatPatched] HOW to use  the  ColmapForVisSatPatched (Issue #1)





 
Have you build the original colmap library without errors?

**Comment by SBCV** [comment]
What I mean is: build the [standard colmap library](https://colmap.github.io/) first, following the instructions [here](https://colmap.github.io/install.html), to see if everything (i.e. nvidia driver, cuda installation) is correctly set up.
Afterwards, try apply the patch files and build the project again.

**Comment by ouyuanzheng** [comment]
Thank you very much for your suggestion! When installing patch files, I don't understand how to proceed with these two steps:


How should I specifically operate these two steps?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月16日(星期天) 晚上7:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SBCV/ColmapForVisSatPatched] HOW to use  the  ColmapForVisSatPatched (Issue #1)





 
What I mean is: build the standard colmap library first, following the instructions here, to see if everything (i.e. nvidia driver, cuda installation) is correctly set up.
 Afterwards, try apply the patch files and build the project again.

**Comment by SBCV** [comment]
> I want to know the sentence 'Finally, apply the satellite specific patches with:
$PathToColmapForVisSatPatched/apply_ Patches. sh $PathToColmapToBePatched ", what should I do specifically?

I do not really understand your question. The command
`$PathToColmapForVisSatPatched/apply_patches.sh $PathToColmapToBePatched`
has to be executed in the terminal like all the other commands in the instructions, such as
`chmod +x $PathToColmapForVisSatPatched/apply_patches.sh`.
The variables $PathToColmapForVisSatPatched and $PathToColmapToBePatched are defined with 
```
PathToColmapForVisSatPatched="/path/to/ColmapForVisSatPatched"
PathToColmapToBePatched="path/to/ColmapToBePatched"
```
as explained on the[ instruction page](https://github.com/SBCV/ColmapForVisSatPatched).

To summarize, you have to execute the following commands (in the terminal)
```
PathToColmapForVisSatPatched="/path/to/ColmapForVisSatPatched"
PathToColmapToBePatched="path/to/ColmapToBePatched"
git clone https://github.com/SBCV/ColmapForVisSatPatched.git $PathToColmapForVisSatPatched
git clone https://github.com/colmap/colmap.git $PathToColmapToBePatched
cd $PathToColmapToBePatched
git checkout 31df46c6c82bbdcaddbca180bc220d2eab9a1b5e
chmod +x $PathToColmapForVisSatPatched/apply_patches.sh
$PathToColmapForVisSatPatched/apply_patches.sh $PathToColmapToBePatched
```
Of course, you have to adapt the first two paths.

> When installing colmap after installing this patch. Do I need to perform&nbsp;
“apt get install nvidia driver 390 nvidia utils 390 nvidia cuda toolkit” of “ubuntu1804_install_dependencies.sh”file .

If cuda and the nvidia driver are already installed, you not need to change anything

**Comment by ouyuanzheng** [comment]
Ok, I will follow your advice. Thank you so much.




---Original---
From: ***@***.***&gt;
Date: Sun, Apr 16, 2023 20:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SBCV/ColmapForVisSatPatched] HOW to use  the ColmapForVisSatPatched (Issue #1)




  
I want to know the sentence 'Finally, apply the satellite specific patches with:
 $PathToColmapForVisSatPatched/apply_ Patches. sh $PathToColmapToBePatched ", what should I do specifically?
  
I do not really understand your question. The command
 $PathToColmapForVisSatPatched/apply_patches.sh $PathToColmapToBePatched
 has to be executed in the terminal like all the other commands in the instructions, such as
 chmod +x $PathToColmapForVisSatPatched/apply_patches.sh.
 The variables $PathToColmapForVisSatPatched and $PathToColmapToBePatched are defined with
 PathToColmapForVisSatPatched="/path/to/ColmapForVisSatPatched" PathToColmapToBePatched="path/to/ColmapToBePatched"  
as explained on the instruction page.
 
To summarize, you have to execute the following commands (in the terminal)
 PathToColmapForVisSatPatched="/path/to/ColmapForVisSatPatched" PathToColmapToBePatched="path/to/ColmapToBePatched" git clone https://github.com/SBCV/ColmapForVisSatPatched.git $PathToColmapForVisSatPatched git clone https://github.com/colmap/colmap.git $PathToColmapToBePatched cd $PathToColmapToBePatched git checkout 31df46c6c82bbdcaddbca180bc220d2eab9a1b5e chmod +x $PathToColmapForVisSatPatched/apply_patches.sh $PathToColmapForVisSatPatched/apply_patches.sh $PathToColmapToBePatched  
Of course, you have to adapt the first two paths.
  
When installing colmap after installing this patch. Do I need to perform&nbsp;
 “apt get install nvidia driver 390 nvidia utils 390 nvidia cuda toolkit” of “ubuntu1804_install_dependencies.sh”file .
  
If cuda and the nvidia driver are already installed, you not need to change anything

**Comment by WangYu0611** [comment]
Did you succeed install this patched?

**Comment by ouyuanzheng** [comment]
No，I tried to install the patched but failed.



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 21, 2023 11:30 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SBCV/ColmapForVisSatPatched] HOW to use  the ColmapForVisSatPatched (Issue #1)




 
Did you succeed install this patched?
