### ISSUE TITLE
I used the standard installation process, but it gave the following error

### ISSUE THREAD

**Issue by WangYu0611** [SBCV/ColmapForVisSatPatches#2]
(base) wyvizzio@wyvizzio-B660I-AORUS-PRO-DDR4:~/path/to/ColmapToBePatched$ $PathToColmapForVisSatPatched/apply_patches.sh $PathToColmapToBePatched
/path/to/ColmapForVisSatPatched
/path/to/ColmapForVisSatPatched/apply_patches.sh: 第 20 行： cd: path/to/ColmapToBePatched: 没有那个文件或目录
警告：.gitignore 的类型是 100644，应为 100755
错误：打补丁失败：.gitignore:41
错误：.gitignore：补丁未应用
错误：CMakeLists.txt: 没有那个文件或目录
警告：README.md 的类型是 100644，应为 100755
错误：打补丁失败：README.md:1
错误：README.md：补丁未应用
错误：scripts/python/build.py: 没有那个文件或目录
错误：src/base/camera.cc: 没有那个文件或目录
错误：src/base/camera_models.h: 没有那个文件或目录
错误：src/base/cost_functions.h: 没有那个文件或目录
错误：src/base/database_cache.h: 没有那个文件或目录
错误：src/base/reconstruction.cc: 没有那个文件或目录
错误：src/base/reconstruction.h: 没有那个文件或目录
错误：src/controllers/bundle_adjustment.cc: 没有那个文件或目录
错误：src/ui/bundle_adjustment_widget.cc: 没有那个文件或目录
错误：src/exe/colmap.cc: 没有那个文件或目录
错误：src/exe/sfm.cc: 没有那个文件或目录
错误：src/exe/sfm.h: 没有那个文件或目录
错误：src/feature/sift.cc: 没有那个文件或目录
错误：src/mvs/depth_map.cc: 没有那个文件或目录
错误：src/mvs/depth_map.h: 没有那个文件或目录
错误：src/mvs/fusion.cc: 没有那个文件或目录
错误：src/mvs/fusion.h: 没有那个文件或目录
错误：src/mvs/image.cc: 没有那个文件或目录
错误：src/mvs/image.h: 没有那个文件或目录
错误：src/mvs/model.cc: 没有那个文件或目录
错误：src/mvs/model.h: 没有那个文件或目录
错误：src/mvs/patch_match.cc: 没有那个文件或目录
错误：src/mvs/patch_match.h: 没有那个文件或目录
错误：src/mvs/patch_match_cuda.cu: 没有那个文件或目录
错误：src/mvs/patch_match_cuda.h: 没有那个文件或目录
错误：src/mvs/workspace.cc: 没有那个文件或目录
错误：src/mvs/workspace.h: 没有那个文件或目录
错误：src/optim/bundle_adjustment.cc: 没有那个文件或目录
错误：src/optim/bundle_adjustment.h: 没有那个文件或目录
错误：src/sfm/incremental_mapper.cc: 没有那个文件或目录
错误：src/util/option_manager.cc: 没有那个文件或目录
cp: 无法创建普通文件'path/to/ColmapToBePatched/install_without_sudo.sh': 没有那个文件或目录
mkdir: 无法创建目录 “path/to/ColmapToBePatched/ubuntu_scripts”: 没有那个文件或目录
cp: 无法创建普通文件'path/to/ColmapToBePatched/ubuntu_scripts/ubuntu1804_build_colmap.sh': 没有那个文件或目录
cp: 无法创建普通文件'path/to/ColmapToBePatched/ubuntu_scripts/ubuntu1804_install_colmap.sh': 没有那个文件或目录
cp: 无法创建普通文件'path/to/ColmapToBePatched/ubuntu_scripts/ubuntu1804_install_dependencies.sh': 没有那个文件或目录
cp: 无法创建普通文件'path/to/ColmapToBePatched/ubuntu_scripts/ubuntu1804_make_eclipse.sh': 没有那个文件或目录

**Comment by WangYu0611** [comment]
(base) wyvizzio@wyvizzio-B660I-AORUS-PRO-DDR4:~/path/to/ColmapToBePatched$ $PathToColmapForVisSatPatched/apply_patches.sh $PathToColmapToBePatched
/path/to/ColmapForVisSatPatched
/path/to/ColmapForVisSatPatched/apply_patches.sh: line 20: cd: path/to/ColmapToBePatched: No such file or directory
warning: .gitignore has type 100644, expected 100755
error: patch failed: .gitignore:41
error: .gitignore: patch does not apply
error: CMakeLists.txt: No such file or directory
warning: README.md has type 100644, expected 100755
error: patch failed: README.md:1
error: README.md: patch does not apply
error: scripts/python/build.py: No such file or directory
error: src/base/camera.cc: No such file or directory
error: src/base/camera_models.h: No such file or directory
error: src/base/cost_functions.h: No such file or directory
error: src/base/database_cache.h: No such file or directory
error: src/base/reconstruction.cc: No such file or directory
error: src/base/reconstruction.h: No such file or directory
error: src/controllers/bundle_adjustment.cc: No such file or directory
error: src/ui/bundle_adjustment_widget.cc: No such file or directory
error: src/exe/colmap.cc: No such file or directory
error: src/exe/sfm.cc: No such file or directory
error: src/exe/sfm.h: No such file or directory
error: src/feature/sift.cc: No such file or directory
error: src/mvs/depth_map.cc: No such file or directory
error: src/mvs/depth_map.h: No such file or directory
error: src/mvs/fusion.cc: No such file or directory
error: src/mvs/fusion.h: No such file or directory
error: src/mvs/image.cc: No such file or directory
error: src/mvs/image.h: No such file or directory
error: src/mvs/model.cc: No such file or directory
error: src/mvs/model.h: No such file or directory
error: src/mvs/patch_match.cc: No such file or directory
error: src/mvs/patch_match.h: No such file or directory
error: src/mvs/patch_match_cuda.cu: No such file or directory
error: src/mvs/patch_match_cuda.h: No such file or directory
error: src/mvs/workspace.cc: No such file or directory
error: src/mvs/workspace.h: No such file or directory
error: src/optim/bundle_adjustment.cc: No such file or directory
error: src/optim/bundle_adjustment.h: No such file or directory
error: src/sfm/incremental_mapper.cc: No such file or directory
error: src/util/option_manager.cc: No such file or directory
cp: cannot create regular file 'path/to/ColmapToBePatched/install_without_sudo.sh': No such file or directory
mkdir: cannot create directory ‘path/to/ColmapToBePatched/ubuntu_scripts’: No such file or directory
cp: cannot create regular file 'path/to/ColmapToBePatched/ubuntu_scripts/ubuntu1804_build_colmap.sh': No such file or directory
cp: cannot create regular file 'path/to/ColmapToBePatched/ubuntu_scripts/ubuntu1804_install_colmap.sh': No such file or directory
cp: cannot create regular file 'path/to/ColmapToBePatched/ubuntu_scripts/ubuntu1804_install_dependencies.sh': No such file or directory
cp: cannot create regular file 'path/to/ColmapToBePatched/ubuntu_scripts/ubuntu1804_make_eclipse.sh': No such file or directory

**Comment by WangYu0611** [comment]
@SBCV  choud you help me ?

**Comment by SBCV** [comment]
Well, looks like you did not adjust the paths according to your system. 
Like stated in the instructions, you need to adapt 

```
PathToColmapForVisSatPatched="/path/to/ColmapForVisSatPatched"
PathToColmapToBePatched="path/to/ColmapToBePatched"

```

The output of your script posted above shows still a root path of  `path/to`.
I'm pretty sure this path does not exist on your system. (It must point to the location where you downloaded ColmapForVisSatPatched and Colmap)

**Comment by WangYu0611** [comment]
> 嗯，看起来你没有根据你的系统调整路径。 正如说明中所述，您需要适应
> 
> ```
> PathToColmapForVisSatPatched="/path/to/ColmapForVisSatPatched"
> PathToColmapToBePatched="path/to/ColmapToBePatched"
> ```
> 
> 上面发布的脚本的输出仍然显示 `path/to`. 我很确定您的系统上不存在此路径。（它必须指向您下载 ColmapForVisSatPatched 和 Colmap 的位置）

thanks , i understand

**Comment by AcoderSc** [comment]
cver@cver-XPS-8930:~/Test/ColmapToBePatched$ $PathToColmapForVisSatPatched/apply_patches.sh $PathToColmapToBePatched
/home/cver/Test/ColmapForVisSatPatched
error: 打补丁失败：.gitignore:41
error: .gitignore：补丁未应用
error: 打补丁失败：CMakeLists.txt:33
error: CMakeLists.txt：补丁未应用
error: 打补丁失败：README.md:1
error: README.md：补丁未应用
error: 打补丁失败：scripts/python/build.py:118
error: scripts/python/build.py：补丁未应用
error: 打补丁失败：src/base/camera.cc:1
error: src/base/camera.cc：补丁未应用
error: 打补丁失败：src/base/camera_models.h:1
error: src/base/camera_models.h：补丁未应用
error: 打补丁失败：src/base/cost_functions.h:1
error: src/base/cost_functions.h：补丁未应用
error: 打补丁失败：src/base/database_cache.h:1
error: src/base/database_cache.h：补丁未应用
error: 打补丁失败：src/base/reconstruction.cc:1
error: src/base/reconstruction.cc：补丁未应用
error: 打补丁失败：src/base/reconstruction.h:1
error: src/base/reconstruction.h：补丁未应用
error: 打补丁失败：src/controllers/bundle_adjustment.cc:1
error: src/controllers/bundle_adjustment.cc：补丁未应用
error: 打补丁失败：src/ui/bundle_adjustment_widget.cc:97
error: src/ui/bundle_adjustment_widget.cc：补丁未应用
error: 打补丁失败：src/exe/colmap.cc:144
error: src/exe/colmap.cc：补丁未应用
error: 打补丁失败：src/exe/sfm.cc:1
error: src/exe/sfm.cc：补丁未应用
error: 打补丁失败：src/exe/sfm.h:46
error: src/exe/sfm.h：补丁未应用
error: 打补丁失败：src/feature/sift.cc:1
error: src/feature/sift.cc：补丁未应用
error: 打补丁失败：src/mvs/depth_map.cc:1
error: src/mvs/depth_map.cc：补丁未应用
error: 打补丁失败：src/mvs/depth_map.h:1
error: src/mvs/depth_map.h：补丁未应用
error: 打补丁失败：src/mvs/fusion.cc:1
error: src/mvs/fusion.cc：补丁未应用
error: 打补丁失败：src/mvs/fusion.h:1
error: src/mvs/fusion.h：补丁未应用
error: 打补丁失败：src/mvs/image.cc:1
error: src/mvs/image.cc：补丁未应用
error: 打补丁失败：src/mvs/image.h:1
error: src/mvs/image.h：补丁未应用
error: 打补丁失败：src/mvs/model.cc:1
error: src/mvs/model.cc：补丁未应用
error: 打补丁失败：src/mvs/model.h:50
error: src/mvs/model.h：补丁未应用
error: 打补丁失败：src/mvs/patch_match.cc:1
error: src/mvs/patch_match.cc：补丁未应用
error: 打补丁失败：src/mvs/patch_match.h:1
error: src/mvs/patch_match.h：补丁未应用
error: 打补丁失败：src/mvs/patch_match_cuda.cu:1
error: src/mvs/patch_match_cuda.cu：补丁未应用
error: 打补丁失败：src/mvs/patch_match_cuda.h:1
error: src/mvs/patch_match_cuda.h：补丁未应用
error: 打补丁失败：src/mvs/workspace.cc:1
error: src/mvs/workspace.cc：补丁未应用
error: 打补丁失败：src/mvs/workspace.h:1
error: src/mvs/workspace.h：补丁未应用
error: 打补丁失败：src/optim/bundle_adjustment.cc:1
error: src/optim/bundle_adjustment.cc：补丁未应用
error: 打补丁失败：src/optim/bundle_adjustment.h:1
error: src/optim/bundle_adjustment.h：补丁未应用
error: 打补丁失败：src/sfm/incremental_mapper.cc:1
error: src/sfm/incremental_mapper.cc：补丁未应用
error: 打补丁失败：src/util/option_manager.cc:1
error: src/util/option_manager.cc：补丁未应用
mkdir: 无法创建目录"/home/cver/Test/ColmapToBePatched//ubuntu_scripts": 文件已存在
I have encountered the above problem, can you help me @SBCV
