### ISSUE TITLE
ColmapForVisSat can not be builded in Windows

### ISSUE THREAD

**Issue by Frmcio** [SBCV/ColmapForVisSatPatches#3]
Dear @SBCV:
        I use the ColmapForVisSatPatched successfully create the ColmapVisSat , but when I tried to use it to build the software in Windows ,   it cannot build successfully.
        I build the software as follows:First I use the ColmapForVisPatched to patch the lastest Colmap successfully . Secondly I use cmd、cmake and vcpkg create Colmap.sln successfully. Finally I open the Colmap.sln in Visual Studio 2019, and Run the All_Build in Release *64 , but the Colmap cannot create successfully.
         Can you teach me what I should do next?I will be extremely grateful if you can provide me with assistance.
![Error](https://github.com/SBCV/ColmapForVisSatPatched/assets/145120105/29aa2d11-88b2-4acf-80a1-26a0c6cb4c13)

**Comment by SBCV** [comment]
I've never tried to build Colmap under Windows. However, this error looks at first glance like it is not related to the patching of colmap.

Have you tried to build the "original" (i.e. the-non patched) Colmap version und Windows? Did this work?

**Comment by Frmcio** [comment]
Thanks for your reply. I build the original Colmap successfully in the same pc , and it is running properly.

**Comment by Frmcio** [comment]
Thanks for your @SBCV  reply. I build the original Colmap successfully in the same pc , and it is running properly.

**Comment by SBCV** [comment]
Okay, that is a bit weird, since the patches perform only small modifications of the source code (and do not add new libraries or similar).

Did you modify the calls in [apply_patches](https://github.com/SBCV/ColmapForVisSatPatched/blob/main/apply_patches.sh) for windows? This script has been written for Linux. I do not expect it to correctly work under windows. Some modifications will be necessary.

**Comment by Frmcio** [comment]
No, I modify nothing. Could you tell me what I need modify to build the software?

**Comment by SBCV** [comment]
I can not test this under Windows, since I do not have a suitable environment on a Windows PC. Sorry.
